const shortcuts = {
  "Alt+Left": "move to the start of the previous word",
  "Alt+Right": "move to the start of the next word",
  "Ctrl+W": "delete back to the start of the previous word",
  "Alt+D": "delete forward to the start of the next word",
  "Ctrl+A": "move to the start of the line",
  "Ctrl+E": "move to the end of the line",
  "Ctrl+U": "clear the whole line",
};

const help = {
  "%help%": "list all commands (you're looking at it)",
  "%alias% [name[=value]]": "define, list, or query command aliases",
  "%unalias% name": "remove a command alias",
  "%bookmark% add NAME": "save the current directory as NAME",
  "%bookmark% list": "list saved directory bookmarks",
  "%bookmark% remove NAME": "remove a saved directory bookmark",
  "%go% NAME": "go to the directory saved as NAME",
  "PIPELINES": "pipe command output through filters from left to right",
  "  COMMAND | %grep% [-ivn] PATTERN": "keep literal matching lines (-i case-insensitive, -v invert, -n number)",
  "  COMMAND | %head% [N]": "keep the first N lines (default: 10; N must be positive)",
  "  COMMAND | %tail% [N]": "keep the last N lines (default: 10; N must be positive)",
  "  COMMAND | %wc% -l": "print the number of output lines",
  "  %whois% | %grep% -i root | %head% 3": "example of a chained pipeline",
  "%whois%": "list all partners",
  "%whois% [partner]": "learn about a partner",
  "%whois% root": "learn about us",
  "%tldr%": "list all portfolio companies",
  "%tldr% [company_name]": "learn about a portfolio company",
  "%email%": "reach out to us",
  "%twitter%": "twitter accounts",
  "%instagram%": "instagram account",
  "%git%": "this repo",
  "%github%": "all repos",
  "%locate%": "physical address",
  "%www%": "plain-text version of this site",
  "%jobs%": "check out our job openings",
  "%export% NAME=value": "store a variable; without arguments, list all variables sorted by name",
  "%env%": "list all stored variables as NAME=value sorted by name",
  "%unset% NAME": "remove a stored variable",
  "%man% export|env|unset": "command manuals; arguments expand with $NAME or ${NAME}, undefined names become empty, and \\$NAME escapes expansion",
  "%test%": "do not use",
  "%upgrade%": "upgrade to the latest version of Root Ventures",
  "%other%": "try your fav commands (e.g. %ls%, %groups%, %su%)",
};
